### PR TITLE
Updated README file

### PR DESCRIPTION
**Pull request by namansancheti**
Updated the README file as per issue #2

### CODE REVIEW

**Comment by AnnAddicks** [comment]
Hi @namansancheti!  Thanks so much for contributing, I appreciate the help.  Can you make one change to your current documentation?  It looks like the markdown to bold does not work in a hyperlink.  Can you remove the double asterisks from the URI?  

"https://docs.google.com/spreadsheets/d/**1_P9K2asfsITSGEAh7PrPLxncSemNnjXHg3_O3q7OW0k**/edit?usp=sharing"

should instead be "https://docs.google.com/spreadsheets/d/1_P9K2asfsITSGEAh7PrPLxncSemNnjXHg3_O3q7OW0k/edit?usp=sharing"
so users will not see the two ** on either side of the hash.

Otherwise, it looks great and I look forward to accepting your pull request.

**Comment by namansancheti** [comment]
Hi @AnnAddicks,
I have removed the two ** as requested. Please let me know, if any other changes are also required.
Thanks.

**Comment by AnnAddicks** [comment]
Thanks @namansancheti, it looks good!  Let me know if you have a twitter handle you want me to give a shout out to or if you want to learn Golang, I can create an easy fix issue for you to work on.  Otherwise, good luck and thanks for the PR!  

:cake:

**Comment by namansancheti** [comment]
@AnnAddicks , Sure I would love to do so.
My twitter handle is **@namans_26**.
Thanks.

**Pull request merged**
